### ISSUE TITLE
Todo - list

### ISSUE THREAD

**Issue by gspaiva** [gspaiva/development-news#1]
# Gateway
- [x] Create the initial config for the microservices gateway
- [x] Create docker configuration

# Service registery
- [x] Create the initial config for the microservices registry
- [x] Create docker configuration

# Lambda function - Get development news 
- [x] Create a crawler for infoq news
- [x] Create method to make a http post to the crud microservice
- [x] Deploy at Amazon

# Service - CRUD for development news
- [x] Create the initial config for the service
- [x] Create reading news route
- [x] Create create news route
- [x] Create docker configuration
- [ ] Create unit test

# General for microservices
- [x] Create docker-compose configuration
- [ ] Deploy at Amazon

**Comment by gspaiva** [comment]
Fechando. Irei usar o projects do github para melhor gerenciamento.
